version: "3.8"

services:
  back:
    image: rmonico/teste_apontador_backend

    build:
      context: ./backend

    expose:
      - "8080"

    ports:
      - "8080:8080"


  front:
    image: rmonico/teste_apontador_frontend

    build:
      context: ./frontend

    volumes:
      - './frontend:/app'
      - '/app/node_modules'

    ports:
      - "4200:4200"

volumes:
  frontend:
  node_modules:

